name: Test commit & push

on:
  workflow_dispatch:
    inputs:
      mydata:
        description: "data"
        required: true
        default: ""
        
jobs:
  presto-release:
    name: Test commit & push
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout Presto source
        uses: actions/checkout@v4
        with:
          ref: master
          show-progress: false

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Configure Git
        run: |
          git config --global --add safe.directory ${{github.workspace}}
          git config --global user.email "oss-release-bot@prestodb.io"
          git config --global user.name "oss-release-bot"
          git remote set-url origin "https://x-access-token:${{ github.event.inputs.mydata }}@github.com/${{ github.repository }}.git"
          git config pull.rebase false
          git remote -v

      - name: Set Maven version
        run: |
          unset MAVEN_CONFIG && ./mvnw versions:set -DremoveSnapshot -ntp

      - name: Get Presto release version
        id: get-version
        run: |
          PRESTO_RELEASE_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate \
            -Dexpression=project.version -q -ntp -DforceStdout | tail -n 1)
          echo "PRESTO_RELEASE_VERSION=$PRESTO_RELEASE_VERSION"
          echo "PRESTO_RELEASE_VERSION=$PRESTO_RELEASE_VERSION" >> $GITHUB_OUTPUT

      - name: Push release branch
        env:
          PRESTO_RELEASE_VERSION: ${{ steps.get-version.outputs.PRESTO_RELEASE_VERSION }}
        run: |
          date > test.txt
          git add test.txt
          git commit -m 'update test.txt'
          cat test.txt
          git push --follow-tags origin master
          git checkout -b release-${{ env.PRESTO_RELEASE_VERSION }}
          git push origin release-${{ env.PRESTO_RELEASE_VERSION }}
